export enum EventNamesEnum {
  SIGN_IN = 'signin',
  SIGN_OUT = 'signout',
  SIGN_UP = 'signup',
  NEW_PROPERTY_SUBSCRIPTION = 'new_property_subscription',
  TRIGGER_REMOTE_MODAL_LGA = 'trigger_remote_modal_lga',
  TRIGGER_REMOTE_MODAL_LGA_WARD = 'trigger_remote_modal_lga_ward',
  POST_LGA = 'post_lga',
  POST_LGA_WARD = 'post_lga_ward',
  POST_STREET = 'post_street',
  POST_PROPERTY_TYPE = 'post_property_type',
  POST_SUBSCRIBER = 'post_subscriber',
  GENERATE_BILLING = 'generate_billing',
  VIEW_BILLING_DETAILS = 'view_billing_details',
  GET_DEFAULTERS = 'get_defaulters',
  POST_PAYMENT = 'post_payment',
}
